spring.application.name=sarvasya-lms-backend

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/sarvasyalms
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Tenant Limits
app.tenant.limits.users=${LIMIT_USERS:1000}
app.tenant.limits.professors=${LIMIT_PROFESSORS:150}
app.tenant.limits.admins=${LIMIT_ADMINS:10}
 
 # Multipart Configuration
 spring.servlet.multipart.max-file-size=5MB
 spring.servlet.multipart.max-request-size=5MB
